// <auto-generated />
namespace Inventory_Mnagement_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Stocks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stocks));
        
        string IMigrationMetadata.Id
        {
            get { return "202508011107336_Stocks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
