// <auto-generated />
namespace Inventory_Mnagement_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Sales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sales));
        
        string IMigrationMetadata.Id
        {
            get { return "202508010951590_Sales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
